import { useRef } from 'react'
import axios from 'axios'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  const inputRef = useRef<HTMLInputElement>(null)
  const handleClick = (e: any) => {
    e.preventDefault()

    if (!inputRef.current || !inputRef.current.value) return

    axios.get(`/api/add-item?name=${inputRef.current.value}`).then((res) => {
      console.log(res.data)
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form onSubmit={handleClick}>
          <input type="text" ref={inputRef} placeholder="name" />
        </form>
        <button onClick={handleClick}>버튼 클릭</button>
      </main>
    </div>
  )
}
